# cargo-about configuration for generating THIRD-PARTY-LICENSES.
# Run:  cargo about generate about.hbs -o THIRD-PARTY-LICENSES.txt
#
# `accepted` lists every SPDX license that actually appears in the
# dependency tree (verified with `cargo license`). All are permissive or
# file-level weak-copyleft (MPL-2.0) — none impose a copyleft obligation on
# AgentGuard's own source. If a new dependency introduces a license not in
# this list, `cargo about generate` fails loudly so it gets reviewed.
accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "0BSD",
    "Zlib",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CDLA-Permissive-2.0",
    "MPL-2.0",
    "Unlicense",
]
